<vault_unlocking_bytecode> 
<step>                                                            
OP_INPUTINDEX OP_0 OP_NUMEQUAL OP_VERIFY                                  
OP_INPUTINDEX OP_UTXOBYTECODE                                             
OP_INPUTINDEX OP_OUTPUTBYTECODE OP_EQUAL OP_VERIFY                        
OP_INPUTINDEX OP_UTXOTOKENCATEGORY                                        
OP_INPUTINDEX OP_OUTPUTTOKENCATEGORY OP_EQUAL OP_VERIFY                   
OP_INPUTINDEX OP_OUTPUTVALUE <0x2003> OP_GREATERTHAN OP_VERIFY            
OP_INPUTINDEX OP_UTXOTOKENCOMMITMENT OP_BIN2NUM                           
OP_INPUTINDEX OP_OUTPUTTOKENCOMMITMENT                                    
OP_1 OP_PICK OP_3 OP_PICK OP_ADD OP_4 OP_NUM2BIN OP_EQUAL OP_VERIFY       
OP_0 OP_PICK OP_2 OP_ROLL OP_DIV OP_10 OP_MOD OP_0 OP_NUMEQUAL OP_IF      
OP_TXOUTPUTCOUNT OP_1 OP_NUMEQUAL OP_VERIFY                               
OP_ELSE                                                                   
OP_0 OP_PICK OP_SIZE OP_NIP OP_1 OP_PICK OP_CAT                           
OP_2 OP_PICK OP_CAT                                                       
<0xaa20> OP_1 OP_PICK OP_HASH256 OP_CAT <0x87> OP_CAT                     
OP_1 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_1 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_1 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_1 OP_OUTPUTTOKENAMOUNT <0x0040075af07507> OP_NUMEQUAL OP_VERIFY        
OP_1 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_2 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_2 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_2 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_2 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_2 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_3 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_3 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_3 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_3 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_3 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_4 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_4 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_4 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_4 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_4 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_5 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_5 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_5 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_5 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_5 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_6 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_6 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_6 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_6 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_6 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_7 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_7 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_7 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_7 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_7 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
OP_8 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_8 OP_OUTPUTTOKENCATEGORY OP_0 OP_OUTPOINTTXHASH OP_EQUAL OP_VERIFY     
OP_8 OP_OUTPUTTOKENCOMMITMENT OP_0 OP_EQUAL OP_VERIFY                     
OP_8 OP_OUTPUTTOKENAMOUNT OP_1 OP_OUTPUTTOKENAMOUNT OP_NUMEQUAL OP_VERIFY 
OP_8 OP_OUTPUTVALUE <0xe803> OP_NUMEQUAL OP_VERIFY                        
<0x6a04534d50300210000446424348>                                          
OP_3 OP_PICK OP_SIZE OP_NIP OP_CAT OP_3 OP_PICK OP_CAT                    
<0x0108> OP_CAT                                                           
OP_9 OP_OUTPUTBYTECODE OP_1 OP_PICK OP_EQUAL OP_VERIFY                    
OP_9 OP_OUTPUTTOKENCATEGORY OP_0 OP_EQUAL OP_VERIFY                       
OP_9 OP_OUTPUTVALUE OP_0 OP_NUMEQUAL OP_VERIFY                            
OP_TXOUTPUTCOUNT OP_10 OP_NUMEQUAL OP_VERIFY                              
OP_DROP OP_DROP OP_DROP OP_ENDIF                                          
OP_1 OP_NIP OP_NIP                                                        